# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_description', models.TextField()),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('video_order', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='courses.Subject')),
            ],
        ),
    ]
